# Generated by Django 4.2.7 on 2023-11-19 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='avatar')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
